-- this query was inttended to aggregate apacheadmissiondx in the categories defined by the clinical team of this project
-- in a second version we decided to use the original apachedxgroup created by the LCP team and only use our categories to break down the diagnoses within 'Others'
SELECT
  patientunitstayid,
  apacheadmissiondx,
  CASE
     -- For our initial definition of Other and RespMedOther we don't want to write the aggregated version of diagnosis but the actual diagnosis.
     -- We want to break down 'Other' 
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Abdomen only trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Abdomen/extremity trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Abdomen/face trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Abdomen/multiple trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Abdomen/pelvis trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Abdomen/spinal trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Ablation or mapping of cardiac conduction pathway' THEN 'Cardiovascular'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Abscess, neurologic' THEN 'Infx'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Abscess/infection-cranial, surgery for' THEN 'Neurosurgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Acid-base/electrolyte disturbance' THEN 'Renal'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Addisons disease' THEN 'Endocrine'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Adrenal neoplasm (including pheochromocytoma)' THEN 'Oncologic'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Adrenalectomy' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Alcohol withdrawal' THEN 'TOX'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Amputation (non-traumatic)' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Amyotrophic lateral sclerosis' THEN 'Neuro'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Anaphylaxis' THEN 'Allergy'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Anastomosis, vascular' THEN 'Vascular surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Anemia' THEN 'Hematology'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Aneurysm repair, ventricular' THEN 'Vascular surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Aneurysm, abdominal aortic' THEN 'Vascular surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Aneurysm, abdominal aortic; with dissection' THEN 'Vascular surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Aneurysm, abdominal aortic; with rupture' THEN 'Vascular surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Aneurysm, dissecting aortic' THEN 'Vascular surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Aneurysm, thoracic aortic' THEN 'Vascular surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Aneurysm, thoracic aortic; with dissection' THEN 'Vascular surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Aneurysm, thoracic aortic; with rupture' THEN 'Vascular surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Aneurysm/pseudoaneurysm, other' THEN 'Vascular surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Aneurysms, repair of other (except ventricular)' THEN 'Vascular surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Angina, stable (asymp or stable pattern of symptoms w/meds)' THEN 'Cardiovascular'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Angina, unstable (angina interferes w/quality of life or meds are tolerated poorly)' THEN 'Cardiovascular'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Aortic and Mitral valve replacement' THEN 'Cardiac Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Aortic valve replacement (isolated)' THEN 'Cardiac Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Apnea-sleep; surgery for (i.e., UPPP - uvulopalatopharyngoplasty)' THEN apacheadmissiondx
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Apnea, sleep' THEN apacheadmissiondx
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Appendectomy' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='ARDS-adult respiratory distress syndrome, non-cardiogenic pulmonary edema' THEN apacheadmissiondx
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Arrest, respiratory (without cardiac arrest)' THEN 'Arrest, respiratory (without cardiac arrest)'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Arteriovenous malformation, surgery for' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Arthritis, rheumatoid' THEN 'Rheumotology'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Arthritis, septic' THEN 'Infx'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Asthma' THEN 'Pulmonary'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Atelectasis' THEN apacheadmissiondx
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Atrial Septal Defect (ASD) Repair' THEN 'Cardiac Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Biopsy, brain' THEN 'Neurosurgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Biopsy, open lung' THEN apacheadmissiondx
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Bladder repair of perforation/rupture' THEN 'Urology'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Bleeding-lower GI, surgery for' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Bleeding-other GI, surgery for' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Bleeding-upper GI, surgery for' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Bleeding-variceal, surgery for (excluding vascular shunting-see surgery for portosystemic shunt)' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Bleeding, GI from esophageal varices/portal hypertension' THEN 'GI'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Bleeding, GI-location unknown' THEN 'GI'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Bleeding, lower GI' THEN 'GI'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Bleeding, upper GI' THEN 'GI'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Blood transfusion reaction' THEN 'Hematology'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Bullectomy' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Burn' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Burr hole placement' THEN 'Neurosurgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='CABG alone, coronary artery bypass grafting' THEN 'Cardiac Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='CABG alone, redo' THEN 'Cardiac Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='CABG redo with other operation' THEN 'Cardiac Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='CABG redo with valve repair/replacement' THEN 'Cardiac Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='CABG with aortic valve replacement' THEN 'Cardiac Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='CABG with double valve repair/replacement' THEN 'Cardiac Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='CABG with mitral valve repair' THEN 'Cardiac Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='CABG with mitral valve replacement' THEN 'Cardiac Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='CABG with other operation' THEN 'Cardiac Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='CABG with pulmonic or tricuspid valve repair or replacement ONLY.' THEN 'Cardiac Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='CABG, minimally invasive; mid-CABG' THEN 'Cardiac Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cancer-colon/rectal, surgery for (including abdominoperineal resections)' THEN 'Oncologic'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cancer-esophageal, surgery for (abdominal approach)' THEN 'Oncologic'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cancer-laryngeal/tracheal, surgery for' THEN 'Oncologic'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cancer-other GI tract, surgery for (i.e., hepatoma, gallbladder etc.)' THEN 'Oncologic'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cancer-small intestinal, surgery for' THEN 'Oncologic'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cancer-stomach, surgery for' THEN 'Oncologic'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cancer, colon/rectal' THEN 'Oncologic'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cancer, esophageal' THEN 'Oncologic'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cancer, laryngeal' THEN 'Oncologic'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cancer, lung' THEN 'Oncologic'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cancer, oral' THEN 'Oncologic'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cancer, oral/sinus, surgery for' THEN 'Oncologic'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cancer, other GI' THEN 'Oncologic'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cancer, pancreatic' THEN 'Oncologic'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cancer, stomach' THEN 'Oncologic'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cancer, tracheal' THEN 'Oncologic'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='CAPD catheter insertion' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cardiac arrest (with or without respiratory arrest; for respiratory arrest see Respiratory System)' THEN 'Cardiovascular'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cardiomyopathy' THEN 'Cardiovascular'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cardiovascular medical, other' THEN 'Cardiovascular'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cardiovascular surgery, other' THEN 'Cardiac Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cellulitis and localized soft tissue infections' THEN 'Infx'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cellulitis and localized soft tissue infections, surgery for' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cerebrospinal fluid leak, surgery for' THEN 'Neurosurgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cesarean section' THEN 'OB/GYN'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Chest pain, epigastric' THEN 'Cardiovascular'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Chest pain, musculoskeletal' THEN apacheadmissiondx
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Chest pain, respiratory' THEN 'Pulmonary'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Chest pain, unknown origin' THEN 'Cardiovascular'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Chest thorax only trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Chest/abdomen trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Chest/extremity trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Chest/face trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Chest/multiple trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Chest/pelvis trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Chest/spinal trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Chest/thorax only trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='CHF, congestive heart failure' THEN 'Cardiovascular'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cholangitis' THEN 'GI'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cholecystectomy/cholangitis, surgery for (gallbladder removal)' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Coagulopathy' THEN 'Hematology'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Coma/change in level of consciousness (for hepatic see GI, for diabetic see Endocrine, if related to cardiac arrest, see CV)' THEN 'Neuro'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Complications for previous spinal cord surgery, surgery for' THEN 'Neurosurgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Complications of prev. peripheral vasc. surgery,surgery for (i.e.ligation of bleeder, exploration and evacuation of hematoma, debridement, pseudoaneurysms, clots, fistula, etc.)' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Complications of previous GI surgery; surgery for (anastomotic leak, bleeding, abscess, infection, dehiscence, etc.)' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Complications of previous open heart surgery (i.e. bleeding, infection etc.)' THEN 'Cardiac Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Complications of previous open-heart surgery, surgery for (i.e. bleeding, infection, mediastinal rewiring,leaking aortic graft etc.)' THEN 'Cardiac Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Congenital Defect Repair (Other)' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Connective tissue disease (mixed)' THEN 'Rheumotology'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Contusion, myocardial (include r/o)' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cosmetic surgery (all)' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cranial nerve, decompression/ligation' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cranioplasty and complications from previous craniotomies' THEN 'Neurosurgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='CVA, cerebrovascular accident/stroke' THEN 'Neuro'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cyst, rupture ovarian' THEN 'OB/GYN'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cystectomy for neoplasm' THEN 'Urology'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Cystectomy, other reasons' THEN 'Urology'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Defibrillator, automatic implantable cardiac; insertion of' THEN 'Cardiovascular'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Devices for spine fracture/dislocation' THEN 'Neurosurgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Diabetic hyperglycemic hyperosmolar nonketotic coma (HHNC)' THEN 'Endocrine'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Diabetic ketoacidosis' THEN 'Endocrine'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Dilatation (with general anesthesia)' THEN apacheadmissiondx
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Dilatation (without general anesthesia)' THEN apacheadmissiondx
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Diverticular disease' THEN 'GI'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Diverticular disease, surgery for' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Drug withdrawal' THEN 'TOX'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Ectopic pregnancy (all)' THEN 'OB/GYN'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Efffusion, pericardial' THEN 'Cardiovascular'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Effusions, pleural' THEN apacheadmissiondx
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Embolectomy (with general anesthesia)' THEN 'Vascular Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Embolectomy (without general anesthesia)' THEN 'Vascular Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Embolus, pulmonary' THEN 'Embolus, pulmonary'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Emphysema/bronchitis' THEN 'Pulmonary'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Encephalitis' THEN 'Infx'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Encephalopathies (excluding hepatic)' THEN 'Neuro'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Encephalopathy, hepatic' THEN 'GI'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Endarterectomy (other vessels)' THEN 'Vascular Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Endarterectomy, carotid' THEN 'Vascular Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Endocarditis' THEN 'Infx'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Esophageal surgery, other' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Exenteration, pelvic-female' THEN 'OB/GYN'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Extremity only trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Extremity only trauma, surgery for' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Extremity/face trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Extremity/face trauma, surgery for' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Extremity/multiple trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Extremity/multiple trauma, surgery for' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Face only trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Face only trauma, surgery for' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Face/multiple trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Face/multiple trauma, surgery for' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Facial surgery (if related to trauma, see Trauma)' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Fistula/abscess, surgery for (not inflammatory bowel disease)' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Fracture-pathological, non-union, non-traumatic, for fractures due to trauma see Trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Fusion-spinal/Harrington rods' THEN 'Neurosurgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Gastrostomy' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Genitourinary medical, other' THEN 'Urology'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Genitourinary surgery, other' THEN 'Urology'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='GI abscess/cyst' THEN 'GI'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='GI Abscess/cyst-primary, surgery for' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='GI medical, other' THEN 'GI'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='GI obstruction' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='GI obstruction, surgery for (including lysis of adhesions)' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='GI perforation/rupture' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='GI perforation/rupture, surgery for' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='GI surgery, other' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='GI vascular insufficiency' THEN 'GI'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='GI vascular ischemia, surgery for (resection)' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Graft for dialysis, insertion of' THEN 'Vascular Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Graft, all other bypass (except renal)' THEN 'Vascular Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Graft, all renal bypass' THEN 'Urology'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Graft, aorto-femoral bypass' THEN 'Vascular Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Graft, aorto-iliac bypass' THEN 'Vascular Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Graft, femoral-femoral bypass' THEN 'Vascular Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Graft, femoral-popliteal bypass' THEN 'Vascular Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Graft, removal of infected vascular' THEN 'Vascular Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Grafting, skin (all)' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Guillain-Barre syndrome' THEN apacheadmissiondx
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Head only trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Head/abdomen trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Head/chest trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Head/extremity trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Head/face trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Head/multiple trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Head/pelvis trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Head/spinal trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Heart transplant' THEN 'Cardiac Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Heat exhaustion/stroke' THEN apacheadmissiondx
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Hematologic medical, other' THEN 'Hematology'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Hematologic surgery, other' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Hematoma subdural, surgery for' THEN 'Neurosurgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Hematoma-epidural, surgery for' THEN 'Neurosurgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Hematoma, epidural' THEN 'Neurosurgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Hematoma, subdural' THEN 'Neurosurgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Hematomas' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Hemorrhage (for gastrointestinal bleeding GI-see GI system) (for trauma see Trauma)' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Hemorrhage, intra/retroperitoneal' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Hemorrhage, postpartum' THEN 'OB/GYN'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Hemorrhage/hematoma-intracranial, surgery for' THEN 'Neurosurgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Hemorrhage/hematoma, intracranial' THEN 'Neurosurgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Hemorrhage/hemoptysis, pulmonary' THEN apacheadmissiondx
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Hemothorax' THEN apacheadmissiondx
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Hepatic failure, acute' THEN 'GI'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Hepato-renal syndrome' THEN 'GI'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Hernia-hiatal, esophageal surgery for' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Herniorrhaphy' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Hip replacement, total (non-traumatic)' THEN 'Orthopedic Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Hydrocephalus, obstructive' THEN 'Neurosurgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Hypertension-pulmonary, primary/idiopathic' THEN 'Pulmonary'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Hypertension, uncontrolled (for cerebrovascular accident-see Neurological System)' THEN 'Cardiovascular'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Hyperthermia' THEN apacheadmissiondx
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Hyperthyroid storm/crisis' THEN 'Endocrine'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Hypoglycemia' THEN 'Endocrine'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Hypothermia' THEN apacheadmissiondx
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Hypothyroid/myxedema' THEN 'Endocrine'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Hypovolemia (including dehydration, Do not include shock states)' THEN apacheadmissiondx
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Hysterectomy for cancer with or without lymph node dissection' THEN 'OB/GYN'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Hysterectomy for other benign neoplasm/fibroids' THEN 'OB/GYN'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Infarction, acute myocardial (MI)' THEN 'Cardiovascular'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Infection/abscess, other surgery for' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Inflammatory bowel disease' THEN 'GI'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Inflammatory bowel disease, surgery for' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Kidney transplant' THEN 'Transplant Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Kidney-pancreas transplant' THEN 'Transplant Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Knee replacement, total (non-traumatic)' THEN 'Orthopedic Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Laminectomy/spinal cord decompression (excluding malignancies)' THEN 'Neurosurgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Leukemia, acute lymphocytic' THEN 'Oncologic'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Leukemia, acute myelocytic' THEN 'Oncologic'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Leukemia, chronic lymphocytic' THEN 'Oncologic'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Leukemia, chronic myelocytic' THEN 'Oncologic'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Leukemia, other' THEN 'Oncologic'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Liver transplant' THEN 'Transplant Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Lung transplant, bilateral' THEN 'Transplant Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Lung transplant, single' THEN 'Transplant Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Lupus, systemic' THEN 'Rheumotology'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Lymph node dissection, pelvic or retroperitoneal (female)' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Lymph node dissection, pelvic or retroperitoneal (male)' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Lymphoma, Hodgkins' THEN 'Oncologic'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Lymphoma, non-Hodgkins' THEN 'Oncologic'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Lymphoma, non-Hodgkins, surgery for (including staging)' THEN 'Oncologic'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Mastectomy (all)' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Meningitis' THEN 'Infx'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Metabolic/endocrine medical, other' THEN 'Endocrine'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Metabolic/endocrine surgery, other' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='MI admitted > 24 hrs after onset of ischemia' THEN 'Cardiovascular'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Mitral valve repair' THEN 'Cardiac Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Mitral valve replacement' THEN 'Cardiac Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Monitoring, hemodynamic (pre-operative evaluation)' THEN apacheadmissiondx
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Musculoskeletal medical, other' THEN 'MSK'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Myasthenia gravis' THEN 'Neurologic'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Myositis, viral' THEN 'Infx'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Near drowning accident' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Neoplasm-cranial, surgery for (excluding transphenoidal)' THEN 'Neurosurgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Neoplasm-spinal cord, surgery or other related procedures' THEN 'Neurosurgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Neoplasm, neurologic' THEN 'Oncologic'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Nephrectomy (other reasons)' THEN 'Urology'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Nephrectomy for neoplasm' THEN 'Urology'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Neurologic medical, other' THEN 'Neuro'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Neurologic surgery, other' THEN 'Neurosurgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Neuromuscular medical, other' THEN 'Neuro'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Neutropenia' THEN 'Hematology'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Nontraumatic coma due to anoxia/ischemia' THEN 'Neuro'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Obesity-morbid, surgery for' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Obstruction due to neoplasm ,surgery for; (with or without ileal-conduit)' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Obstruction due to nephrolithiasis, surgery for (with or without ileal-conduit)' THEN 'Urology'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Obstruction-airway (i.e., acute epiglottitis, post-extubation edema, foreign body, etc)' THEN apacheadmissiondx
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Obstruction/other, surgery for (with or without ileal conduit)' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Oophorectomy with or without salpingectomy with or without lymph node dissection' THEN 'OB/GYN'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Orthopedic surgery, other' THEN 'Orthopedic Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Overdose, alcohols (bethanol, methanol, ethylene glycol)' THEN 'TOX'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Overdose, analgesic (aspirin, acetaminophen)' THEN 'TOX'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Overdose, antidepressants (cyclic, lithium)' THEN 'TOX'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Overdose, other toxin, poison or drug' THEN 'TOX'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Overdose, sedatives, hypnotics, antipsychotics, benzodiazepines' THEN 'TOX'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Overdose, street drugs (opiates, cocaine, amphetamine)' THEN 'TOX'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Palsy, cranial nerve' THEN 'Neuro'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Pancreatitis' THEN 'GI'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Pancreatitis, surgery for' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Pancytopenia' THEN 'Hematology'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Papillary muscle rupture' THEN 'Cardiovascular'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Parathyroidectomy' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Pelvic relaxation (cystocele, rectocele, etc.)' THEN 'OB/GYN'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Pelvis/extremity trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Pelvis/face trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Pelvis/hip trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Pelvis/multiple trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Pelvis/spinal trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Pericardial effusion/tamponade' THEN 'Cardiovascular'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Pericardiectomy (total/subtotal)' THEN 'Cardiac Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Pericarditis' THEN 'Cardiovascular'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Peritoneal lavage' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Peritonitis' THEN 'GI'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Peritonitis, surgery for' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Pneumonia, aspiration' THEN 'Infx'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Pneumonia, bacterial' THEN 'Infx'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Pneumonia, fungal' THEN 'infx'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Pneumonia, other' THEN 'infx'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Pneumonia, parasitic (i.e., Pneumocystic pneumonia)' THEN 'infx'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Pneumonia, viral' THEN 'infx'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Pneumothorax' THEN apacheadmissiondx
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Poisoning, carbon monoxide, arsenic, cyanide' THEN 'TOX'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Pre-eclampsia/eclampsia' THEN 'OB/GYN'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Prostatectomy, suprapubic; for benign prostatic hypertrophy' THEN 'Urology'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Prostatectomy, suprapubic; for cancer' THEN 'Urology'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Pulmonary valve surgery' THEN 'Cardiac Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Renal bleeding' THEN 'Urology'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Renal failure, acute' THEN 'Renal'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Renal infection/abscess' THEN 'Infx'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Renal neoplasm, cancer' THEN 'Oncologic'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Renal obstruction' THEN 'Urology'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Respiratory - medical, other' THEN apacheadmissiondx
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Respiratory surgery, other' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Restrictive lung disease (i.e., Sarcoidosis, pulmonary fibrosis)' THEN apacheadmissiondx
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Rhabdomyolysis' THEN apacheadmissiondx
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Rhythm disturbance (atrial, supraventricular)' THEN 'Cardiovascular'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Rhythm disturbance (conduction defect)' THEN 'Cardiovascular'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Rhythm disturbance (ventricular)' THEN 'Cardiovascular'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Seizures (primary-no structural brain disease)' THEN 'Neuro'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Seizures-intractable, surgery for' THEN 'Neurosurgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Sepsis, cutaneous/soft tissue' THEN 'Infx'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Sepsis, GI' THEN 'Infx'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Sepsis, gynecologic' THEN 'Infx'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Sepsis, other' THEN 'Infx'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Sepsis, pulmonary' THEN 'Infx'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Sepsis, renal/UTI (including bladder)' THEN 'Infx'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Sepsis, unknown' THEN 'Infx'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Shock, cardiogenic' THEN 'Cardiovascular'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Shunt-portosystemic, surgery for' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Shunt, peritoneal-venous; surgery for' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Shunts and revisions' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Sickle cell crisis' THEN 'Hematology'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Skin surgery, other' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Smoke inhalation' THEN 'TOX'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Spinal cord only trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Spinal cord surgery, other' THEN 'Neurosurgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Spinal/extremity trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Spinal/face trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Spinal/multiple trauma' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Splenectomy' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Stereotactic procedure' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Subarachnoid hemorrhage/arteriovenous malformation' THEN 'Neurosurgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Subarachnoid hemorrhage/intracranial aneurysm' THEN 'Neurosurgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Subarachnoid hemorrhage/intracranial aneurysm, surgery for' THEN 'Neurosurgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Tamponade, pericardial' THEN 'Cardiovascular'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Thoracotomy for benign tumor (i.e. mediastinal chest wall mass, thymectomy)' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Thoracotomy for bronchopleural fistula' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Thoracotomy for esophageal cancer' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Thoracotomy for lung cancer' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Thoracotomy for lung reduction' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Thoracotomy for other malignancy in chest' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Thoracotomy for other reasons' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Thoracotomy for pleural disease' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Thoracotomy for thoracic/respiratory infection' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Thrombectomy (with general anesthesia)' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Thrombectomy (without general anesthesia)' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Thrombocytopenia' THEN 'Hematology'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Thrombosis, vascular (deep vein)' THEN 'Cardiovascular'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Thrombus, arterial' THEN 'Vascular surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Thyroid neoplasm' THEN 'Oncologic'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Thyroidectomy' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Thyroidectomy and Parathyroidectomy' THEN 'Surgical'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Toxicity, drug (i.e., beta blockers, calcium channel blockers, etc.)' THEN 'TOX'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Tracheostomy' THEN apacheadmissiondx
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Transphenoidal surgery' THEN 'Neurosurgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Transplant, other' THEN 'Transplant Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Trauma medical, other' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Trauma surgery, other' THEN 'Trauma'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Tricuspid valve surgery' THEN 'Cardiac Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Tumor removal, intracardiac' THEN 'Cardiac Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='TURP, transurethral prostate resection for benign prostatic hypertrophy' THEN 'Urology'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='TURP, transurethral prostate resection for cancer' THEN 'Urology'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Ulcer disease, peptic' THEN 'GI'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Vascular medical, other' THEN 'Cardiovascular'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Vascular surgery, other' THEN 'Vascular Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Vasculitis' THEN 'Rheumotology'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Vena cava clipping' THEN 'Vascular Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Vena cava filter insertion' THEN 'Vascular Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Ventricular Septal Defect (VSD) Repair' THEN 'Cardiac Surgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Ventriculostomy' THEN 'Neurosurgery'
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Weaning from mechanical ventilation (transfer from other unit or hospital only)' THEN apacheadmissiondx
    WHEN apachedxgroup = 'Other' AND apacheadmissiondx ='Whipple-surgery for pancreatic cancer' THEN 'Surgical'
    -- 'RespMedOther'
    WHEN apachedxgroup = 'RespMedOther' AND apacheadmissiondx ='Apnea-sleep; surgery for (i.e., UPPP - uvulopalatopharyngoplasty)' THEN apacheadmissiondx
    WHEN apachedxgroup = 'RespMedOther' AND apacheadmissiondx ='Apnea, sleep' THEN apacheadmissiondx
    WHEN apachedxgroup = 'RespMedOther' AND apacheadmissiondx ='ARDS-adult respiratory distress syndrome, non-cardiogenic pulmonary edema' THEN apacheadmissiondx
    WHEN apachedxgroup = 'RespMedOther' AND apacheadmissiondx ='Arrest, respiratory (without cardiac arrest)' THEN 'Arrest, respiratory (without cardiac arrest)'
    WHEN apachedxgroup = 'RespMedOther' AND apacheadmissiondx ='Atelectasis' THEN apacheadmissiondx
    WHEN apachedxgroup = 'RespMedOther' AND apacheadmissiondx ='Biopsy, open lung' THEN apacheadmissiondx
    WHEN apachedxgroup = 'RespMedOther' AND apacheadmissiondx ='Effusions, pleural' THEN apacheadmissiondx
    WHEN apachedxgroup = 'RespMedOther' AND apacheadmissiondx ='Embolus, pulmonary' THEN 'Embolus, pulmonary'
    WHEN apachedxgroup = 'RespMedOther' AND apacheadmissiondx ='Guillain-Barre syndrome' THEN apacheadmissiondx
    WHEN apachedxgroup = 'RespMedOther' AND apacheadmissiondx ='Hemorrhage/hemoptysis, pulmonary' THEN apacheadmissiondx
    WHEN apachedxgroup = 'RespMedOther' AND apacheadmissiondx ='Hemothorax' THEN apacheadmissiondx
    WHEN apachedxgroup = 'RespMedOther' AND apacheadmissiondx ='Obstruction-airway (i.e., acute epiglottitis, post-extubation edema, foreign body, etc)' THEN apacheadmissiondx
    WHEN apachedxgroup = 'RespMedOther' AND apacheadmissiondx ='Pneumothorax' THEN apacheadmissiondx
    WHEN apachedxgroup = 'RespMedOther' AND apacheadmissiondx ='Respiratory - medical, other' THEN apacheadmissiondx
    WHEN apachedxgroup = 'RespMedOther' AND apacheadmissiondx ='Restrictive lung disease (i.e., Sarcoidosis, pulmonary fibrosis)' THEN apacheadmissiondx
    WHEN apachedxgroup = 'RespMedOther' AND apacheadmissiondx ='Tracheostomy' THEN apacheadmissiondx
    WHEN apachedxgroup = 'RespMedOther' AND apacheadmissiondx ='Weaning from mechanical ventilation (transfer from other unit or hospital only)' THEN apacheadmissiondx
    ELSE apachedxgroup
    END AS apachedxgroup_mod,
    apachedxgroup,
FROM
  `physionet-data.eicu_crd_derived.apache_groups`
