---
title: "02_training_model"
author: "Miguel Ángel Armengol & Jay Chandra"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_notebook:
    code_folding: hide
    number_sections: yes
    theme: flatly
    toc: yes
    toc_float: yes

knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = paste0(substr(inputFile,1,nchar(inputFile)-4)," ",Sys.Date(),'.html')) })
---


# Environment

```{r message=FALSE, warning=FALSE}
require(foreign)
require(ggplot2)
require(MASS)
require(Hmisc)
require(reshape2)
require(boot)
require(pROC)
library(mlbench)
library(MLmetrics)
library(plotly)
library(gbm)
library(xgboost)
library(oddsratio)
library(ggplot2)
library(survey)
library(table1)
library(sandwich)
library(dplyr)
#library(robustHD)
library(mgcv)
library(tidyverse)
library(caret)
center_scale <- function(x) {
    scale(x, scale = FALSE)
}
```

# GAM analysis Fluid Balance

```{r}
# Build the model
model <- gam(fluid_balance_72  ~
                         s(leaking_index) + age_fixed + gender + apache_iv + final_charlson_score
                         ,data=selected_df_fluid, family = gaussian) 
# Make predictions
predictions <- model %>% predict(selected_df_fluid)
# Model performance
data.frame(
  RMSE = RMSE(predictions, selected_df_fluid$fluid_balance_72),
  R2 = R2(predictions, selected_df_fluid$fluid_balance_72)
)
summary(model)
ggplot(selected_df_fluid, aes(leaking_index, fluid_balance_72) ) +
  stat_smooth(method = gam, formula = y ~ s(x)) +
  labs(y="Fluid Balance 36h-84h (ml)", x = "VLI")+
  theme_classic()
ggsave("eICU_fluid.png", dpi = 1200)
```

```{r}
# Build the model
model <- gam(hosp_mortality  ~
                         s(leaking_index) + age_fixed + gender + apache_iv + final_charlson_score,data=selected_df_mortality, family = binomial)
# Make predictions
predictions <- model %>% predict(selected_df_mortality)
# Model performance
data.frame(
  RMSE = RMSE(predictions, selected_df_mortality$hosp_mortality),
  R2 = R2(predictions, selected_df_mortality$hosp_mortality)
)
summary(model)
ggplot(selected_df_mortality, aes(leaking_index, hosp_mortality) ) +
  stat_smooth(method = gam, formula = y ~ s(x)) + 
  labs(y="In-Hospital Death", x = "VLI")+
  theme_classic()
ggsave("eICU_mortality.png", dpi = 1200)
```


```{r}
OR_table<-as.data.frame(round(exp(cbind(OR=coef(model), confint.default(model))),2))
options(scipen=999) # disable scientific notation
OR_table

#Generate plot of the odds ratio for quartiles of CLI measured against mortality
labels<-c('VLI Q2', 'VLI Q3', 'VLI Q4')
number_of_exposures<-length(labels)+1
df <- data.frame(yAxis = 2:number_of_exposures,
                 boxOdds = OR_table$OR[2:number_of_exposures] ,
                 boxCILow = OR_table$`2.5 %`[2:number_of_exposures],  
                 boxCIHigh = OR_table$`97.5 %`[2:number_of_exposures]
)
#df <- df[order(df$boxOdds),]
p<-ggplot(df, aes(x = boxOdds
                  , y = labels
                  )) + 
  geom_vline(aes(xintercept = 1), size = .1, linetype = "dashed") + 
  geom_errorbarh(aes(xmax = boxCIHigh, xmin = boxCILow)
                 , size = .5
                 , height = .2
                 , color = "gray50") +
  geom_point(size = 2, color = "#2980b9") +
  #coord_trans(x = scales:::exp_trans(1.01)) +
  #scale_y_continuous(breaks = c(-1:1),labels = c(-1:1)) +
  theme_bw()+
  theme(panel.grid.minor = element_blank()) +
  ylab("Exposure") +
  xlab("Odds ratio")
p<-ggplotly(p)
p<-ggplotly(p%>%layout(hovermode = 'compare'))
p
ggsave("eICU_odds.png", dpi = 1200)
```

