---
title: "Tables"
author: "Miguel ?ngel Armengol de la Hoz"
output:
  html_document:
    toc: true
    theme: united
---

# Environment

```{r}
library(tableone)
library(magrittr)
library(table1)
library(kableExtra)
library(dplyr)
library(magrittr)
```

# Table 1 

## Stratified by top apache groups

```{r}
vars_in_table1<-c("age_fixed","gender","HospitalLOS","unitType","hospitalAdmitSource","actualicumortality","unabridgedunitlos","unabridgedhosplos","unabridgedactualventdays","predictedHospitalMortality","apache_iv","final_charlson_score","lactate_fst","lactate_max","lactate_num","lactate_num_first3days","lactate_bin_first3days","lactateredrawn_wt8hrs_bin_first3days","mins_from_first_elev_to_test", "mins_from_first_elev_to_test","lactate_max_first3days_type","apache_strat")

table1_dataset<-lactate_df[,vars_in_table1]


stratifyby<-'apache_strat'

cat_variables<-rep(NA, length(vars_in_table1))
label(table1_dataset$age_fixed)<-'Age'
label(table1_dataset$gender)<-'Gender'
label(table1_dataset$unitType)<-'ICU Type'
label(table1_dataset$apache_iv)<-'Apache Score'
label(table1_dataset$final_charlson_score)<-'Charlson Comorbidity Index'


# detects whether a variable is categorical or not
cont<-1
for (i in 1:length(vars_in_table1) ) {
  if ( n_distinct(table1_dataset[vars_in_table1[i] ])<=10 ) {
    print(i)
    print(vars_in_table1[i])
    print(names(table1_dataset[vars_in_table1[i]]))
    cat_variables[cont]<-names(table1_dataset[vars_in_table1[i]])
    cont<-cont+1
  }
}  

vars_in_table1_nostrat<-c("age_fixed","gender","HospitalLOS","unitType","hospitalAdmitSource","actualicumortality","unabridgedunitlos","unabridgedhosplos","unabridgedactualventdays","predictedHospitalMortality","apache_iv","final_charlson_score","lactate_fst","lactate_max","lactate_num","lactate_num_first3days","lactate_bin_first3days","lactateredrawn_wt8hrs_bin_first3days","mins_from_first_elev_to_test","lactate_max_first3days_type")

cat_variables<-cat_variables[!is.na(cat_variables)]
table1_base<-print(CreateTableOne(vars = vars_in_table1_nostrat
                                  , strata = stratifyby
                                  , factorVars = cat_variables
                                  
    ,data = table1_dataset, addOverall=T),varLabels = T
    ,nonnormal = c('leaking_index'))
# run this in console for html output, the code below uses kableExtra::
starification_cats<-n_distinct(table1_dataset[,stratifyby])
table1_base %>%
  kbl(caption = "Table 1" , align = "c") %>%
  kable_classic_2(full_width = F, html_font = "Cambria")%>%
  add_header_above(c("Top apache groups" = 9 ))
```

## Stratified by top apache groups & lactate cat & teachingstatus

```{r}
vars_in_table1<-c("age_fixed","gender","HospitalLOS","unitType","hospitalAdmitSource","actualicumortality","unabridgedunitlos","unabridgedhosplos","unabridgedactualventdays","predictedHospitalMortality","apache_iv","final_charlson_score","lactate_fst","lactate_max","lactate_num","lactate_num_first3days","lactate_bin_first3days","lactateredrawn_wt8hrs_bin_first3days","mins_from_first_elev_to_test", "mins_from_first_elev_to_test","lactate_max_first3days_type","apache_strat","teachingstatus")
# we are extracting top n apache groups


# apache_cats_array<-unique(lactate_df$apache_strat)
# # "CardiacArrest" "Sepsis"        "CVA"           "ACS"           "GIBleed"      
# 
 table1_dataset<-lactate_df[,vars_in_table1]
# table1_dataset%<>%filter(apache_strat=='GIBleed')


stratifyby<-c('lactate_max_first3days_type','apache_strat','teachingstatus')

cat_variables<-rep(NA, length(vars_in_table1))
label(table1_dataset$age_fixed)<-'Age'
label(table1_dataset$gender)<-'Gender'
label(table1_dataset$unitType)<-'ICU Type'
label(table1_dataset$apache_iv)<-'Apache Score'
label(table1_dataset$final_charlson_score)<-'Charlson Comorbidity Index'


# detects whether a variable is categorical or not
cont<-1
for (i in 1:length(vars_in_table1) ) {
  if ( n_distinct(table1_dataset[vars_in_table1[i] ])<=10 ) {
    print(i)
    print(vars_in_table1[i])
    print(names(table1_dataset[vars_in_table1[i]]))
    cat_variables[cont]<-names(table1_dataset[vars_in_table1[i]])
    cont<-cont+1
  }
}  

vars_in_table1_nostrat<-c("age_fixed","gender","HospitalLOS","unitType","hospitalAdmitSource","actualicumortality","unabridgedunitlos","unabridgedhosplos","unabridgedactualventdays","predictedHospitalMortality","apache_iv","final_charlson_score","lactate_fst","lactate_max","lactate_num","lactate_num_first3days","lactate_bin_first3days","lactateredrawn_wt8hrs_bin_first3days","mins_from_first_elev_to_test","lactate_max_first3days_type")

cat_variables<-cat_variables[!is.na(cat_variables)]
table1_base<-print(CreateTableOne(vars = vars_in_table1_nostrat
                                  , strata = stratifyby
                                  , factorVars = cat_variables
                                  
    ,data = table1_dataset, addOverall=T),varLabels = T
    ,nonnormal = c('leaking_index'))
# run this in console for html output, the code below uses kableExtra::
starification_cats<-n_distinct(table1_dataset[,stratifyby])

table1_base %>%
  kbl(caption = "Table 1" , align = "c") %>%
  kable_classic_2(full_width = F, html_font = "Cambria")
  # add_header_above(c("Top apache groups" = 7 ))


```
